apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-host
  namespace: keycloak
data:
  keycloak-host: {{ .Values.keycloakHost }}
  keycloak-host-url: {{ printf "https://%s" .Values.keycloakHost }}

