apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-host
  namespace: keycloak
data:
  keycloak-host: {{ .Values.keycloakHost }}
  keycloak-host-url: {{ printf "http://%s" .Values.keycloakHost }}
  keycloak-external-host: {{ .Values.keycloakExternalHost }}
  keycloak-external-url: {{ printf "https://%s" .Values.keycloakExternalHost }}

