apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: keycloak
spec:
  hosts:
    - "*"
  gateways:
  - keycloak

  http:
  - match:
      - uri:
          prefix: /
    route:
    - destination:
        host: keycloak.keycloak.svc.cluster.local
        port:
          number: 80
    headers:
      request:
        set:
          x-forwarded-proto: https
