---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.websub.serviceName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # pod is considered part of the release.
    "helm.sh/hook": post-install
spec:
  replicas: {{ .Values.services.websub.podconfig.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.services.websub.serviceName }}
  minReadySeconds: {{ .Values.services.websub.podconfig.minReadySeconds }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.services.websub.podconfig.maxUnavailable }}
      maxSurge: {{ .Values.services.websub.podconfig.maxSurge }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.websub.serviceName }}
        exportLogs: {{ .Values.exportLogs }}
    spec:
      containers:
        - name: {{ .Values.services.websub.serviceName }}
          image: {{ .Values.services.websub.dockerImage }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          {{ $resources := .Values.services.websub.podconfig.resources }}
          {{- include "resourcesDefinition" (dict "res" $resources) | indent 8 }}
          env:
            - name: hub_config_file_url_env
              value: {{ .Values.hub.websub.hub_config_file_url_env }}
          ports:
            - containerPort: {{ .Values.hub.websub.port }}
