image:
  repository: bitnami/keycloak
  ## This tag works well.  Remove this line if you would like to pull the latest version
  tag: 14.0.0-debian-10-r24
service:
  type: ClusterIP

auth:
  adminUser: admin

## Disable ingress as we use Istio
ingress:
  enabled: false
  hostname: 
  annotations:
    ingress.kubernetes.io/class: nginx

proxyAddressForwarding: true

replicaCount: 2

# Enable if replicaCount > 1
serviceDiscovery:
  enabled: true

resources:
  limits: {}
  #   cpu: 250m
  #   memory: 1Gi
  requests: 
    cpu: 200m
    memory: 1000Mi

rbac:
  create: true
  rules:
    - apiGroups:
        - ""
      resources:
        - pods
      verbs:
        - get
        - list
