image:
  repository: bitnami/keycloak
  tag: 11.0.2-debian-10-r12
service:
  type: ClusterIP

auth:
  adminUser: admin

ingress:
  enabled: true
  hostname: iam.mosip.net
  annotations:
    ingress.kubernetes.io/class: nginx

proxyAddressForwarding: true

replicaCount: 1 

# Enable if replicaCount > 1
serviceDiscovery:
  enabled: false

resources:
  limits: {}
  #   cpu: 250m
  #   memory: 1Gi
  requests: 
    cpu: 200m
    memory: 1000Mi
