---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.services.activemq.podconfig.replicas }} 
  selector:
    matchLabels:
      app: {{ .Values.name }}
  minReadySeconds: {{ .Values.services.activemq.podconfig.minReadySeconds }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.services.activemq.podconfig.maxUnavailable }}
      maxSurge: {{ .Values.services.activemq.podconfig.maxSurge }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        exportLogs: {{ .Values.exportLogs }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.docker.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        {{ $resources := .Values.services.activemq.podconfig.resources }}
        {{- include "resourcesDefinition" (dict "res" $resources) | indent 8 }}
        env:
        - name: ACTIVEMQ_MIN_MEMORY
          value: {{ .Values.docker.minmemory }}
        - name: ACTIVEMQ_MAX_MEMORY
          value: {{ .Values.docker.maxmemory }}
        - name: ACTIVEMQ_STORAGE_USAGE 
          value: {{ .Values.docker.storeusage }}
        - name: ACTIVEMQ_TEMP_USAGE
          value: {{ .Values.docker.tempusage }}
        - name: ACTIVEMQ_ADMIN_LOGIN
          value: admin
        - name: ACTIVEMQ_ADMIN_PASSWORD
          value: {{ .Values.adminPassword }} 
        #- name: ACTIVEMQ_LOGLEVEL
        #  value: "DEBUG, logfile, console"
        ports:
        - containerPort: {{ .Values.docker.containerPort }} 
        livenessProbe:
          tcpSocket:
            port: {{ .Values.docker.containerPort }}  # All defaults used
          periodSeconds: {{ .Values.probe.livenessPeriod }}
          timeoutSeconds: {{ .Values.probe.timeout }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.docker.containerPort }}  # All defaults used
          periodSeconds: {{ .Values.probe.period }}
          timeoutSeconds: {{ .Values.probe.timeout }}
        startupProbe:
          tcpSocket:
            port: {{ .Values.docker.containerPort }}  # All defaults used
          failureThreshold: {{ .Values.probe.failureThreshold }}
          periodSeconds: {{ .Values.probe.startupPeriod }}
        volumeMounts:
        - name: q-data
          mountPath: {{ .Values.mountPath }} 
        - name: activemq-xml-conf
          mountPath: "/opt/activemq/conf/activemq.xml" # hardcoded path for activemq.xml inside container
          subPath: "activemq.xml"
        - name: activemq-log4j-props
          mountPath: "/opt/activemq/conf/log4j.properties" # hardcoded path for log4j.properties inside container
          subPath: "log4j.properties"
        - name: activemq-supervisor-conf
          mountPath: "/etc/supervisor/conf.d/activemq.conf" # hardcoded path for activemq.conf (supervisor conf)
          subPath: "activemq.conf"
      volumes:
      - name: q-data
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.name }} 
      - name: activemq-xml-conf
        configMap:
          name: {{ .Values.name }}
      - name: activemq-log4j-props
        configMap:
          name: {{ .Values.name }}-log4j-props
      - name: activemq-supervisor-conf
        configMap:
          name: {{ .Values.name }}-supervisor-conf 
