- name: Manage public ports with firewalld ansible module 
  hosts: console mzmaster mzworkers dmzmaster dmzworkers
  gather_facts: no
  become: true
  tasks:
    - name: print group name
      debug:
        msg: '{{ hostvars[inventory_hostname].group_names[0] }}'
      register: group_name
    
    - name: Set port list for console
      set_fact:
        port_list:
          - { port: 22/tcp,       state: enabled }
          - { port: 53/tcp,       state: enabled }
          - { port: 53/udp,       state: enabled }
          - { port: 80/tcp,       state: enabled }
          - { port: 443/tcp,      state: enabled }
          - { port: 30090/tcp,    state: enabled }
          - { port: 2049/tcp,     state: enabled }
          - { port: 30000-32767/tcp, state: enabled }
          - { port: 30000-32767/udp, state: enabled }
      when: group_name.msg == 'console'

    - name: Set port list for mzmaster & dmzmaster
      set_fact:
        port_list:
          - { port: 22/tcp,          state: enabled }
          - { port: 80/tcp,          state: enabled }
          - { port: 443/tcp,         state: enabled }
          - { port: 2379-2380/tcp,   state: enabled }
          - { port: 6443/tcp,        state: enabled }
          - { port: 10250/tcp,       state: enabled }
          - { port: 10251/tcp,       state: enabled }
          - { port: 10252/tcp,       state: enabled }
          - { port: 10255/tcp,       state: enabled }
          - { port: 8472/udp,        state: enabled }
          - { port: 8472/tcp,        state: enabled }
          - { port: 30000-32767/tcp, state: enabled }
          - { port: 30000-32767/udp, state: enabled }
      when: group_name.msg == 'mzmaster' or group_name.msg == 'dmzmaster'

    - name: Set port list for mzworkers for dmzworkers
      set_fact:
        port_list:
          - { port: 22/tcp,        state: enabled }
          - { port: 80/tcp,        state: enabled }
          - { port: 443/tcp,       state: enabled }
          - { port: 10250/tcp,     state: enabled }
          - { port: 10251/tcp,     state: enabled }
          - { port: 10255/tcp,     state: enabled }
          - { port: 8472/udp,        state: enabled }
          - { port: 8472/tcp,        state: enabled }
          - { port: 30000-32767/tcp, state: enabled }
          - { port: 30000-32767/udp, state: enabled }
      when: group_name.msg == 'mzworkers' or group_name.msg == 'dmzworkers' 

    - name: Install & Enable ports
      block:
        - name: Install firewalld
          yum:
            name: firewalld
            state: latest
        - name: start firewalld
          service:
            name: firewalld
            state: started
            enabled: yes
        - name: Enable ports on the list
          firewalld:
            zone: public
            port: "{{ item.port }}"
            permanent: true
            state: "{{ item.state }}"
          loop:
            "{{ port_list }}"
          notify:
            - Restart firewalld
      become: yes
      when: port_list is not undefined or port_list != []
  handlers:
    - name: Restart firewalld
      service:
        name: firewalld
        state: restarted
        
