# Install and init postgres
#

- import_playbook: postgres-install.yml
  when: postgres.external == false

- import_playbook: postgres-init-db.yml
  when: postgres.postgres_init.init == true

#- import_playbook: postgres-init.yml
#  when: postgres.init == true

