# All plays related to registration processor module
#

# Prep
- hosts: console
  tasks:
    - {name: 'Create landing folder', file: {name: '{{regproc.nfs.landing_folder}}', state: directory}, become: yes}
    - {name: 'Create regproc folder', file: {name: '{{regproc.nfs.regproc_path}}',   state: directory}, become: yes}

- hosts: console
  roles:
    - { role: k8sHealthCheckPod, vars: { dirName: '{{regproc.nfs.stages.group2.path}}',
                                         owner: '{{regproc.nfs.stages.group2.path_owner}}',
                                         group: '{{regproc.nfs.stages.group2.path_group}}',
                                         healthCheckBashFile: '{{regproc.nfs.stages.group2.healthCheckBashFile}}',
                                         healthCheckUrlListFile: '{{regproc.nfs.stages.group2.healthCheckUrlListFile}}',
                                }
    }


# Run DMZ regproc
- hosts: console
  vars:
    kube_config: '{{clusters.dmz.kube_config}}'
    install_name: 'dmzregproc'
    helm_chart: '{{charts_root}}/dmzregproc'
    is_template: true  
    helm_namespace: 'default'
    helm_values: '{{charts_root}}/dmzregproc/values.template.j2'
    helm_strings: ''
  roles:
    - {role:  helm, tags: [dmzregproc]}

## Run MZ regproc
- hosts: console
  vars:
    kube_config: '{{clusters.mz.kube_config}}'
    install_name: 'regproc'
    helm_chart: '{{charts_root}}/regproc'
    is_template: true  
    helm_namespace: 'default'
    helm_values: '{{charts_root}}/regproc/values.template.j2'
    helm_strings: ''
  roles:
    - {role:  helm, tags: [regproc]}
 
