apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-operator-my
spec:
  profile: default
  # This is done to merge multiple slashes in http URLs, otherwise, MOSIP APIs may not work
  meshConfig:
    pathNormalization:
      normalization: MERGE_SLASHES
    defaultConfig:
      gatewayTopology:
        numTrustedProxies: 2
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          serviceAnnotations:
            service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
            service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
            service.beta.kubernetes.io/aws-load-balancer-internal: "true"
