- name: Add mosip helm repository
  shell: "{{helm_cli_path}}/helm repo add mosip https://mosip.github.io/mosip-helm"

- name: update helm repository
  shell: "{{helm_cli_path}}/helm repo update"

- name: create secret "postgres-postgresql" for postgres-init DB
  shell: '{{kc1}} -n {{ postgres_init.namespace }} create secret generic postgres-postgresql --from-literal=postgresql-password={{ postgres.password }} --dry-run=client -o yaml | {{kc1}} -n {{ postgres_init.namespace }}  apply -f - '

- name: convert values.template.j2 to values.yaml
  template:
      src: '{{install_root}}/roles/postgres-init-db/meta/values.template.j2'
      dest: '{{install_root}}/roles/postgres-init-db/meta/values.yaml'

- name: Initiailized postgres DB
  shell: "{{helm1}} -n {{ postgres_init.namespace }} install postgres-init mosip/postgres-init -f {{install_root}}/roles/postgres-init-db/meta/values.yaml --version {{ postgres_init.chart_version }} --wait"

- name: create secret "db-common-secrets" for postgres-init DB
  shell: '{{kc1}} -n {{ postgres_init.namespace }} create secret generic db-common-secrets  --from-literal=db-dbuser-password={{ postgres.password }} --dry-run=client -o yaml | {{kc1}} -n {{ postgres_init.namespace }}  apply -f - '
