- name: Install Development tools
  yum:
      name: @development-tools
      state: present
  become: yes

- name: Install python3-devel
  yum:
      name: python3-devel
      state: present
  become: yes

- name: Install postgresql-libs
  yum:
      name: postgresql-libs
      state: present
  become: yes

- name: Install postgresql-devel
  yum:
      name: postgresql-devel
      state: present
  become: yes

- name: Install pandas via pip3
  pip:
      name: psycopg2
      state: latest
      executable: pip3
  become: yes
