apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serviceName }} 
  namespace: {{ .Release.Namespace }} 
  labels:
    app: {{ .Values.serviceName }}
spec:
  replicas: {{ .Values.services.mosip_file_server.podconfig.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.serviceName }} 
  minReadySeconds: {{ .Values.services.mosip_file_server.podconfig.minReadySeconds }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.services.mosip_file_server.podconfig.maxUnavailable }}
      maxSurge: {{ .Values.services.mosip_file_server.podconfig.maxSurge }}
  template:
    metadata:
      labels:
        app: {{ .Values.serviceName }} 
        exportLogs: {{ .Values.exportLogs }}
    spec:
      containers:
      - name: {{ .Values.serviceName }} 
        image: {{ .Values.docker.image }} 
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        - name: artifactory_url_env
          value: {{ .Values.artifactoryUrl }}
        - name: host_url_env
          value: {{ .Values.host }}
        - name: clientid_env
          value: {{ .Values.clientid }}
        - name: clientsecret_env
          value: {{ .Values.secret }}
        ports:
        - containerPort: {{ .Values.docker.ports.containerPort }}

        volumeMounts:
        - name: mosip-file-server-volume
          mountPath: {{ .Values.mountPath }}
      volumes:
      - name: mosip-file-server-volume
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.name }}
