dbUserPasswords:
  dbuserPassword: KQbhy58GYP

databases:
  mosip_master:
    enabled: true

  mosip_audit:
    enabled: false

  mosip_keymgr:
    enabled: false 

  mosip_kernel:
    enabled: false

  mosip_idmap:
    enabled: false

  mosip_prereg:
    enabled: false

  mosip_idrepo:
    enabled: false

  mosip_ida:
    enabled: false

  mosip_credential:
    enabled: false

  mosip_regprc:
    enabled: false

  mosip_regdevice:
    enabled: false

  mosip_authdevice:
    enabled: false

  mosip_pms:
    enabled: false

  mosip_websub:
    enabled: false

