- include_vars: '{{versions_file}}' # Need for resolving various versions

- name: create {{mosip_file_server.nfs_path}} directory
  file:
    name: '{{mosip_file_server.nfs_path}}'
    state: directory
    owner: mosipuser
  become: yes

- name: controller yml to json
  template:
    src: controller.yml.j2
    dest: '{{tmp_dir}}/controller.json'

- name: Copy new conf file
  copy:
    src: '{{tmp_dir}}/controller.json'
    dest: '{{mosip_file_server.nfs_path}}/controller.json'
  become: yes

- name: context yml to json
  template:
    src: mosip-context.yml.j2
    dest: '{{tmp_dir}}/mosip-context.json'

- name: Copy new conf file
  copy:
    src: '{{tmp_dir}}/mosip-context.json'
    dest: '{{mosip_file_server.nfs_path}}/mosip-context.json'
  become: yes

- name: Authenticate in auth maanger
  shell: 'curl -s -D - -o /dev/null -X "POST" \
    "{{site.sandbox_public_url}}/v1/authmanager/authenticate/clientidsecretkey" \
    -H "accept: */*" \
    -H "Content-Type: application/json" \
    -d "{
    "id": "string",
    "version": "string",
    "requesttime": "{{ansible_date_time.date.iso8601_micro}}",
    "metadata": {},
    "request": {
      "clientId": "mosip-regproc-client",
      "secretKey": "{{secret.keycloak.mosip_regproc_client}}",
      "appId": "regproc"
      }
    }" | sed -n "/authorization:/,/\;.*/p" |  sed "s/.*authorization://; s/$\n.*//" | awk "NR==1{print $1}"'
  register: token

- name: Check Token
  shell: 'echo {{token}}'


- name: get public key from keymanager
  shell: 'curl -X "GET" \
            --cookie "Authorization={{token}}" \
            "$host_url_env/v1/keymanager/getCertificate?applicationId=KERNEL&referenceId=SIGN" \
            -H "accept: */*" | sed "s/.*certificate\":\"//g" | sed "s/\".*//g"'
  register: certificate

- name: Check Token
  shell: 'echo {{certificate}}'

- name: public key yml to json
  template:
    src: public-key.yml.j2
    dest: '{{tmp_dir}}/public-key.json'

- name: Copy new json file
  copy:
    src: '{{tmp_dir}}/public-key.json'
    dest: '{{mosip_file_server.nfs_path}}/public-key.json'
  become: yes