- include_vars: '{{versions_file}}' # Need for resolving various versions

- name: create {{mosip_file_server.nfs_path}} directory
  file:
    name: '{{mosip_file_server.nfs_path}}'
    state: directory
    owner: mosipuser

- name: controller yml to json
  template:
    src: controller.yml.j2
    dest: '{{tmp_dir}}/controller.json'

- name: Copy new conf file
  copy:
    src: '{{tmp_dir}}/controller.json'
    dest: '{{mosip_file_server.nfs_path}}/controller.json'
  become: yes

- name: context yml to json
  template:
    src: mosip-context.yml.j2
    dest: '{{tmp_dir}}/mosip-context.json'

- name: Copy new conf file
  copy:
    src: '{{tmp_dir}}/mosip-context.json'
    dest: '{{mosip_file_server.nfs_path}}/mosip-context.json'
  become: yes


#- name: vccontext yml to json
#  template:
#    src: vccontext.yml.j2
#    dest: '{{tmp_dir}}/vccontext.jsonld'

#- name: Copy new conf file
#  copy:
#    src: '{{tmp_dir}}/vccontext.jsonld'
#    dest: '{{mosip_file_server.nfs_path}}/vccontext.jsonld'
#  become: yes
    
