apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: internal
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway-internal
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - api-internal.sandbox.xyz.net
