apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.key-migrator.serviceName }}
  namespace: {{ .Release.Namespace }} 
spec:
  ports:
  - port: {{ .Values.services.key-migrator.servicePort }}
    targetPort: {{ .Values.services.key-migrator.containerPort }}
  selector:
    app: {{ .Values.services.key-migrator.serviceName }}

