- name: Install Development tools
  yum:
      name: "@Development tools"
      state: present
  become: yes

- name: Install python3-devel
  yum:
      name: python3-devel
      state: present
  become: yes

- name: Install postgresql-libs
  yum:
      name: https://centos.pkgs.org/7/postgresql-13-x86_64/postgresql13-libs-13.5-1PGDG.rhel7.x86_64.rpm.html
      state: present
  become: yes

- name: Install postgresql-devel
  yum:
      name: https://centos.pkgs.org/7/postgresql-13-x86_64/postgresql13-devel-13.5-1PGDG.rhel7.x86_64.rpm.html
      state: present
  become: yes

- name: Install psycopg2 via pip3
  pip:
      name: psycopg2
      state: latest
      executable: pip3
  become: yes
