- name: Install Development tools
  yum:
      name: "@Development tools"
      state: present
  become: yes

- name: Install python3-devel
  yum:
      name: python3-devel
      state: present
  become: yes

- name: Install centos-release-scl
  yum:
      name: centos-release-scl
      state: present
  become: yes

- name: Install postgresql13
  yum:
      name: postgresql13
      state: present
  become: yes

- name: Install postgresql13-libs
  yum:
      name: postgresql13-libs
      state: present
  become: yes

- name: Install postgresql13-devel
  yum:
      name: postgresql13-devel
      state: present
  become: yes

- name: Install psycopg2 via pip3
  pip:
      name: psycopg2
      state: latest
      executable: pip3
  become: yes
