gitRepo:
  uri: https://github.com/mosip/mosip-config
  version: 1.1.5_v3
  ## Folders within the base repo where properties may be found.
  searchFolders: ""
  private: false
  ## User name of user who has access to the private repo. Ignore for public repo
  username: ""
  token: ""
