## The data here is  of generic interest to modules in different namespaces hence this is marked as global.
apiVersion: v1
kind: ConfigMap
metadata:
  name: global
  namespace: default
data:
  mosip-api-host-url: https://api.sandbox.mosip.net
  is_glowroot_env: absent

